mkdir Est Ouest Centre
cd Est
mkdir "Esi"
cd "Esi"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  de Sétif 1 - Ferhat Abbas"
cd "Université  de Sétif 1 - Ferhat Abbas"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université de Tébessa - Larbi Tébessi"
cd "Université de Tébessa - Larbi Tébessi"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  de Annaba - Badji Mokhtar"
cd "Université  de Annaba - Badji Mokhtar"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université de Bordj Bou Arréridj - Mohamed Bachir El Ibrahimi"
cd "Université de Bordj Bou Arréridj - Mohamed Bachir El Ibrahimi"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  de Khenchela - Abbas Laghrour"
cd "Université  de Khenchela - Abbas Laghrour"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  de Constantine 1 - Frères Mentouri"
cd "Université  de Constantine 1 - Frères Mentouri"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  de Oum El Bouaghi - Larbi Ben M'hidi"
cd "Université  de Oum El Bouaghi - Larbi Ben M'hidi"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
cd ../Ouest
mkdir "Universitéd'Oran1 - Ahmed Ben Bella"
cd "Universitéd'Oran1 - Ahmed Ben Bella"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université de Béchar - Mohamed Tahri"
cd "Université de Béchar - Mohamed Tahri"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  de Mascara - Mustapha Stambouli"
cd "Université  de Mascara - Mustapha Stambouli"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université de Saida - Tahar Moulay"
cd "Université de Saida - Tahar Moulay"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  de Tlemcen - Abou Bekr Belkaid"
cd "Université  de Tlemcen - Abou Bekr Belkaid"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  d'Adrar - Ahme   d Draya"
cd "Université  d'Adrar - Ahme   d Draya"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  de Tiaret - Ibn Khaldoun"
cd "Université  de Tiaret - Ibn Khaldoun"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  Sidi Bel Abbès - Djillali Liabes"
cd "Université  Sidi Bel Abbès - Djillali Liabes"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
cd ../Centre
mkdir "Université d'Alger 1 - Benyoucef Benkhedda"
cd "Université d'Alger 1 - Benyoucef Benkhedda"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  de Bouira - Akli Mohand Oulhadj"
cd "Université  de Bouira - Akli Mohand Oulhadj"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  de Djelfa - Ziane Achour"
cd "Université  de Djelfa - Ziane Achour"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université de Ghardaia"
cd "Université de Ghardaia"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  de Khemis Miliana - Djilali Bounaama"
cd "Université  de Khemis Miliana - Djilali Bounaama"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  Médéa - Yahia Farès"
cd "Université  Médéa - Yahia Farès"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université de Tamenghasset"
cd "Université de Tamenghasset"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université des sciences et de la technologie d'Alger, Houari Boumediène"
cd "Université des sciences et de la technologie d'Alger, Houari Boumediène"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université de Béjaia - Abderrahmane Mira"
cd "Université de Béjaia - Abderrahmane Mira"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  de Boumerdès - M'hamed Bougara"
cd "Université  de Boumerdès - M'hamed Bougara"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université  Blida 1 - Saad Dahlab"
cd "Université  Blida 1 - Saad Dahlab"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
mkdir "Université de Tizi Ouzou - Mouloud Maameri"
cd "Université de Tizi Ouzou - Mouloud Maameri"
mkdir "Archi"
mkdir "TPGO"
mkdir "Comp"
mkdir "ML"
mkdir "Res"
mkdir "ALSDS"
mkdir "OPTIM"
mkdir "SSR"
mkdir "SYSR"
cd ..
